from .bank import Bank
from .contract import Contract
from .contract_owner import ContractOwner
from .contract_subject import ContractSubject
from .contract_type import ContractType
from .locality import Locality
from .owner import Owner
from .owner import OwnerType
from .ownership import Ownership
from .payment import Payment
from .plot import Plot
from .plot_use_type import PlotUseType
from .sublocality import Sublocality
from .user import User
